
---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "E:/NornirAutoSubbnetter/inventory/hosts.yaml"
        group_file: "E:/NornirAutoSubbnetter/inventory/groups.yaml"
        defaults_file: "E:/NornirAutoSubbnetter/inventory/defaults.yaml"
        
runner:
    plugin: threaded
    options:
        num_workers: 100